# Managing Risk & Threat Models


Lab Length
Medium/Average (~10-20 mins)

Goal
SOME Goal

== Lab 2. Managing Risk & Threat Models


Risk management is the process of identifying and assessing risks and creating a plan to minimize or control those risks and their potential impact on an organization. A risk is a potential for loss or damage. Risks can come from a variety of places such as legal liability, natural disasters, accidents, management errors, or cybersecurity threats.

== 2.1 Risk management steps

=== 2.1.1 Risk identification

Identify and describe potential risks. Types of risks could include financial risks, operational risks (such as risks to a supply chain), project risks, business risks, and market risks—among others. Identified risks should be recorded in a risk register or be documented in some way.

=== 2.1.2 Risk analysis

Determine the probability of a new risk happening by analyzing the risk factors and documenting potential consequences.

=== 2.1.3 Risk assessment and evaluation

Using internal audits and risk analysis, determine the magnitude of a risk. You’ll also need to decide what level of risk is acceptable, and what needs to be dealt with immediately.  

=== 2.1.4 Risk mitigation
Once you’ve determined the priority and importance of risks, you can proceed with a risk response strategy to minimize or control the risk. 

=== 2.1.5 Risk monitoring
Risks and metrics need to be continuously monitored to make sure that risk mitigation plans are working, or to keep you aware if a risk becomes a greater threat.

== 2.2 Risk management approaches

The main risk management approaches include avoidance, reduction, sharing, and retention.

=== 2.2.1 Risk avoidance

Risk avoidance involves stopping and avoiding any activities that could lead to a risk.

=== 2.2.2 Risk reduction

Risk reduction is focused on actions that will reduce the probability of a risk occurring or the impact of a risk.

=== 2.2.3 Risk sharing

Risk sharing is when an organization will transfer or share part of the risk with another organization. An example is outsourcing manufacturing or customer service functions to a third party.

=== 2.2.4 Risk retention

Risk retention occurs when risks have been evaluated and the organization decides to accept the potential risk. No action is taken to mitigate the risk, but a contingency plan may still be put in place.

== Risk Management Examples

