# Creating a system baseline


Lab Length
Medium/Average (~5-10 mins)

Goal
Capture a consistant machine state

== 3.0 Capture machine baseline

We need to capture starting point for our systems.

There are a few different ways:

* sosreport
* Ansible facts
* Insights (out of scope for this lab)
* Satellite (out of scope for this lab)

In this lab scenario we are working on an air-gapped system (Not connected to the internet).

The first best way to do this is to use a built-in utility.

We are go use the built in sos utility, aka sosreport.

=== 3.1 Sos utility

With the sos utility, you can collect configuration, diagnostic, and troubleshooting data, and provide those files to Red Hat Technical Support.
This is a great way to help troubleshoot and see the system changes on your system.

The sos utility allows to collect various debugging information from one or more systems, optionally clean sensitive data, and upload it in a form of a report to Red Hat.
More specifically, the three sos components do the following:

* '''sos report''' collects debugging information from one system.

* '''sos collect''' allows to run and collect individual sos reports from a specified set of nodes.

* '''sos clean''' obfuscates potentially sensitive information such as user names, host names, IP or MAC addresses, or other user-specified data.

The information collected in a report contains configuration details, system information, and diagnostic information from a RHEL system, such as:

* The running kernel version
* Loaded kernel modules
* System and service configuration files
* Diagnostic command output
* A list of installed packages

The sos utility writes the data it collects to an archive named sosreport-<host_name>-<support_case_number>-<YYYY-MM-DD>-<unique_random_characters>.tar.xz

So if you work in an airgapped environment, you can still collect and send data to Red Hat or to your Own IT group.

=== 3.1 Installing the sos package from the command line

To use the sos utility, install the sos package.

**Prerequisites**

You need 'root' privileges.

**Procedure**

Install the 'sos' package.

[source,ini,role=execute,subs=attributes+]
----
sudo dnf install sos
----

**Verification steps**

Use the rpm utility to verify that the sos package is installed.

[source,ini,role=execute,subs=attributes+]
----
sudo rpm -q sos
sos-4.2-15.el9.noarch
----

=== 3.3. Generating an sos report from the command line

Use the 'sos report' command to gather an sos report from a RHEL server.

**Prerequisites**

* You have installed the sos package.
* You need root privileges.

**Procedure**

Run the sos report command and follow the on-screen instructions.

You can add the --upload option to transfer the sos report to Red Hat immediately after generating it.

[source,ini,role=execute,subs=attributes+]
----
sudo sos report
----

=== 3.3.1 (Optional) If you have already opened a Technical Support case with Red Hat,
enter the case number to embed it in the sos report file name,
and it will be uploaded to that case if you specified the --upload option.

If you do not have a case number, leave this field blank.
Entering a case number is optional and does not affect the operation of the sos utility.

=== 3.4 Take note of the sos report file name displayed at the end of the console output.

i.e. /var/tmp/sosreport-bastion-2024-04-15-outurcc.tar.xz

=== 3.5 Capturing Ports, Protocalls, and Services with Anisble

Here's an example of an Ansible playbook that gathers facts from a RHEL 9 machine and creates a report with hardware information, software, services, and system details along with the current date, open your favorite text editor, and create a file named 'PPS_Gather_And_Report.yml'

[source,ini,role=execute,subs=attributes+]
----
---
- name: Gather Facts and Generate Report
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Capture current date
      set_fact:
        current_date: "{{ ansible_date_time.iso8601 }}"

    - name: Gather hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"
      register: hostname_output

    - name: Gather OS version
      ansible.builtin.debug:
        msg: "OS Version: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Gather network information
      ansible.builtin.debug:
        msg: "Network Info: {{ ansible_all_ipv4_addresses }}"

    - name: Gather open ports, protocols, and running services
      ansible.builtin.shell: "ss -tulnp"
      register: open_ports_output

    - name: Generate report
      ansible.builtin.template:
        src: report_template.j2
        dest: "{{ ansible_hostname }}_{{ current_date }}_system_report.txt"
      vars:
        hostname: "{{ ansible_hostname }}"
        os_version: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
        network_info: "{{ ansible_all_ipv4_addresses }}"
        open_ports_info: "{{ open_ports_output.stdout_lines }}"

----

Save and exit that file.

Then open your favorite text editor, and create a jinja2 template  named 'Jreport_template.j2'

[source,ini,role=execute,subs=attributes+]
----
System Report - Generated on {{ current_date }}

Hostname: {{ hostname }}

OS Version: {{ os_version }}

Network Info: {{ network_info | join(', ') }}

Open Ports, Protocols, and Running Services:
{% for line in open_ports_info %}
{{ line }}
{% endfor %}
----

Now It's time for you to run your ansible playbook.

[source,ini,role=execute,subs=attributes+]
----
ansible-playbook PPS_Gather_And_Report.yml

----

This will run it on the localhost and write the report with the hostname and time dates stamp it was run for the file.




