# Creating a system baseline


Lab Length
Medium/Average (~5-10 mins)

Goal
Capture a consistant machine state

== 3.0 Capture machine baseline

We need to capture starting point for our systems.

There are a few different ways:

* sosreport
* Ansible facts
* Insights (out of scope for this lab)
* Satellite (out of scope for this lab)

In this lab scenario we are working on an air-gapped system (Not connected to the internet).

The first best way to do this is to use a built-in utility.

We are go use the built in sos utility, aka sosreport.

=== 3.1 Sos utility

With the sos utility, you can collect configuration, diagnostic, and troubleshooting data, and provide those files to Red Hat Technical Support.
This is a great way to help troubleshoot and see the system changes on your system.

The sos utility allows to collect various debugging information from one or more systems, optionally clean sensitive data, and upload it in a form of a report to Red Hat.
More specifically, the three sos components do the following:

* '''sos report''' collects debugging information from one system.

* '''sos collect''' allows to run and collect individual sos reports from a specified set of nodes.

* '''sos clean''' obfuscates potentially sensitive information such as user names, host names, IP or MAC addresses, or other user-specified data.

The information collected in a report contains configuration details, system information, and diagnostic information from a RHEL system, such as:

* The running kernel version
* Loaded kernel modules
* System and service configuration files
* Diagnostic command output
* A list of installed packages

The sos utility writes the data it collects to an archive named sosreport-<host_name>-<support_case_number>-<YYYY-MM-DD>-<unique_random_characters>.tar.xz

=== 3.1 Installing the sos package from the command line

To use the sos utility, install the sos package.

**Prerequisites**

You need 'root' privileges.

**Procedure**

Install the 'sos' package.

[source,ini,role=execute,subs=attributes+]
----
sudo dnf install sos
----

**Verification steps**

Use the rpm utility to verify that the sos package is installed.

[source,ini,role=execute,subs=attributes+]
----
sudo rpm -q sos
----

=== 3.3. Generating an sos report from the command line

Use the 'sos report' command to gather an sos report from a RHEL server.

**Prerequisites**

* You have installed the sos package.
* You need root privileges.

**Procedure**

Run the sos report command and follow the on-screen instructions.

You can add the --upload option to transfer the sos report to Red Hat immediately after generating it.

[source,ini,role=execute,subs=attributes+]
----
sudo sos report
----

=== 3.3.1 (Optional) If you have already opened a Technical Support case with Red Hat,
enter the case number to embed it in the sos report file name,
and it will be uploaded to that case if you specified the --upload option.

If you do not have a case number, leave this field blank.
Entering a case number is optional and does not affect the operation of the sos utility.

=== 3.4 Take note of the sos report file name displayed at the end of the console output.

i.e. /var/tmp/sosreport-bastion-2024-04-15-outurcc.tar.xz

=== 3.5 Cleaning an sos report

If you work in an airgapped environment, you can still collect and send data to Red Hat or to your Own IT group 

The sos utility offers a routine to obfuscate potentially sensitive data, such as 

* user names
* host names
* IP Addresses 
* MAC addresses
* other user-specified keywords. 

The original sos report or sos collect stays unchanged, and a new *-obfuscated.tar.xz file is generated and intended to be shared with a third party.

**Prerequisites** 

* You have generated an sos report or an sos collect tarball.
* (Optional) You have a list of specific keywords beyond the user names, host names, and other data you want to obfuscate.


**Procedure**

* Run the sos clean command on either an sos report or sos collect tarball and follow the on-screen instructions.
** You can add the --keywords option to additionally clean a given list of keywords.
** You can add the --usernames option to obfuscate further sensitive user names.

The automatic user name cleaning will automatically run for users reported through the lastlog file for users with an UID of 1000 and above. This option is used for LDAP users that may not appear as an actual login, but may occur in certain log files.

**Verification steps**

* Verify that the sos clean command created an obfuscated archive and an obfuscation mapping in the /var/tmp/ directory matching the description from the command output.
* Check the *-private_map file for the obfuscation mapping



=== 3.6 Capturing Ports, Protocalls, and Services with Anisble

Here's an example of an Ansible playbook that gathers facts from a RHEL 9 machine and creates a report with hardware information, software, services, and system details along with the current date, open your favorite text editor, and create a file named 'PPS_Gather_And_Report.yml'

In this example we will use Vi text editor.



[source,ini,role=execute,subs=attributes+]
----
---
- name: Gather Facts and Generate Report
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Capture current date
      set_fact:
        current_date: "{{ ansible_date_time.iso8601 }}"

    - name: Gather hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"
      register: hostname_output

    - name: Gather OS version
      ansible.builtin.debug:
        msg: "OS Version: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Gather network information
      ansible.builtin.debug:
        msg: "Network Info: {{ ansible_all_ipv4_addresses }}"

    - name: Gather open ports, protocols, and running services
      ansible.builtin.shell: "ss -tulnp"
      register: open_ports_output

    - name: Generate report
      ansible.builtin.template:
        src: report_template.j2
        dest: "{{ ansible_hostname }}_{{ current_date }}_system_report.txt"
      vars:
        hostname: "{{ ansible_hostname }}"
        os_version: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
        network_info: "{{ ansible_all_ipv4_addresses }}"
        open_ports_info: "{{ open_ports_output.stdout_lines }}"

----

Save and exit that file.

Then open your favorite text editor, and create a jinja2 template  named 'report_template.j2'

[source,ini,role=execute,subs=attributes+]
----
System Report - Generated on {{ current_date }}

Hostname: {{ hostname }}

OS Version: {{ os_version }}

Network Info: {{ network_info | join(', ') }}

Open Ports, Protocols, and Running Services:
{% for line in open_ports_info %}
{{ line }}
{% endfor %}
----

Now It's time for you to run your ansible playbook.

[source,ini,role=execute,subs=attributes+]
----
ansible-playbook PPS_Gather_And_Report.yml

----

This will run it on the localhost and write the report with the hostname and time dates stamp it was run for the file.

You'll have a report that looks something like this.

[source,ini,role=execute,subs=attributes+]
----
System Report - Generated on 2024-04-18T12:38:20Z

Hostname: bastion

OS Version: RedHat 9.3

Network Info: 192.168.0.11

Open Ports, Protocols, and Running Services:
Netid State  Recv-Q Send-Q Local Address:Port Peer Address:PortProcess
udp   UNCONN 0      0          127.0.0.1:323       0.0.0.0:*          
udp   UNCONN 0      0              [::1]:323          [::]:*          
tcp   LISTEN 0      128          0.0.0.0:22        0.0.0.0:*          
tcp   LISTEN 0      128             [::]:22           [::]:*          
tcp   LISTEN 0      4096               *:443             *:*          
tcp   LISTEN 0      4096               *:9090            *:*          
----


