== Ansible 101

=== Introduction to Ansible

Ansible provides open-source automation that reduces complexity and runs everywhere. 

Using Ansible lets you automate virtually any task. 

Here are some common use cases for Ansible:

* Eliminate repetition and simplify workflows
* Manage and maintain system configuration
* Continuously deploy complex software
* Perform zero-downtime rolling updates

Ansible uses simple, human-readable scripts called playbooks to automate your tasks. 

You declare the desired state of a local or remote system in your playbook. 

Ansible ensures that the system remains in that state.

As automation technology, Ansible is designed around the following principles:

* **Agent-less architecture** 
** Low maintenance overhead by avoiding the installation of additional software across IT infrastructure.

* **Simplicity**
** Automation playbooks use straightforward YAML syntax for code that reads like documentation. Ansible is also decentralized, using SSH existing OS credentials to access to remote machines

* **Scalability and flexibility**
** Easily and quickly scale the systems you automate through a modular design that supports a large range of operating systems, cloud platforms, and network devices.

* **Idempotence and predictability**
** When the system is in the state your playbook describes Ansible does not change anything, even if the playbook runs multiple times.

To learn more about ansible check out the Official https://docs.ansible.com/ansible/latest/getting_started/basic_concepts.html[Ansible Commnity Documentation]

We are going to make sure you can get Ansible Installed on RHEL 9.


=== Install Ansible for Red Hat Enterprise Linux 9

If you use Ansible content within Red Hat Enterprise Linux (RHEL), 
you should know that important changes where made with RHEL 8.6 and 9.0.

RHEL 7 and RHEL 8.0-8.5 customers have access to a separate **Ansible Engine** repository. 

In RHEL 8.6 and 9.0, customers will have access to **Ansible Core**, which will be included in the corresponding AppStream repository. 

The move to Ansible Core in RHEL is being made to adapt to changes in the Ansible project.

For more info on the https://www.redhat.com/en/blog/updates-using-ansible-rhel-86-and-90#How%20to%20migrate%20from%20Ansible%20Engine%20to%20Ansible%20Core[difference between Ansible core and engine?]


You'll be using Ansible core with RHEL 9, so lets get it installed.

[source,ini,role=execute,subs=attributes+]
----
sudo dnf install ansible-core -y
----


=== Basic Ansible setup for Red Hat Enterprise Linux 9

I like to create a working directory to work on my ansible projects in my home folder

[source,ini,role=execute,subs=attributes+]
----
mkdir ~/ansible
----

I also then like bring in a deafult ansible config file for later use.

[source,ini,role=execute,subs=attributes+]
----
ansible-config init --disabled > ~/ansible/ansible.cfg
----

We also need to create an inventory file to refference.

The inventory file is where we list our machines we will connect to.

In this lab we will connect to 

* bastion
* node1

We will next create a simple inventory file for ansible to use to connect to the machines.

We will be using the vi file editor.

If you have never worked with vi before, here is a very basic https://www.redhat.com/sysadmin/get-started-vi-editor[How to get started with the Vi editor]

[source,ini,role=execute,subs=attributes+]
----
vi ~/ansible/inventory
----

This will open a new file named inventory.

To edit a file in vi, you will need to change to edit mode.

You will need to type 'i' in your terminal to go into 'insert' mode.

You should now be able to to type, edit and paste into the ternimal to chagne the file.

You will want to copy the following and paste it into the terminal.

[source,ini,role=execute,subs=attributes+]
----
[bastion]
localhost


[nodes]
YourNode1IPaddress

----
Under the nodes section is where you will put your node1 ip addesss you made note of earlier in the workshop.

Next you will need to switch to vi command mode,
you do this by pressing the 'Esc' button on your keyboard.

Now you will want to save and close the vi file,
to do this type ':wq'

This will write the file, and quit the vi program.


=== Basic Ansible smoke ping test

Lets make sure we can connect to both our machines

first lets change dirrectories to our working folder

[source,ini,role=execute,subs=attributes+]
----
cd ~/ansible
----

Then issue a command to check the localhost (bastion) machine

[source,ini,role=execute,subs=attributes+]
----
ansible -m ping -i inventory localhost
----

Then issue a command to check the localhost (bastion) machine
[source,ini,role=execute,subs=attributes+]
----
ansible -m ping -i inventory node1
----

If everything is working correctly you should see something like this in your terminal

[source,ini,role=execute,subs=attributes+]
----
machinehostname | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
---- 

== Reference Documentation

https://www.redhat.com/en/blog/updates-using-ansible-rhel-86-and-90[Updates to using Ansible in RHEL 8.6 and 9.0]

https://www.redhat.com/en/blog/updates-using-ansible-core-in-rhel[Updates to using Ansible Core in Red Hat Enterprise Linux]

https://access.redhat.com/articles/6393321[Using Ansible in RHEL 9]

https://access.redhat.com/articles/3050101[Red Hat Enterprise Linux (RHEL) System Roles]



