# RHPDS Lab Setup


Lab Length
Medium/Average (~10-20 mins)

Goal
Become familiar with the basics of ssh

== 1.1: Introduction

If you are in a live classroom or in a phisical workshop, follow these instructions. 

If you want to do this at home or on your own machine, you can follow the 'lab_1_rhpds_lab_setup.adoc' which is after this page.


In this scenario you are a system administrator given a task to harden a Red Hat Enterprise Linux system. You have no idea what is on the system, what it is running, the hardware, or software installed. You are working on a black box.

You are given credentials that should give you access to the machine. You are given a Jump Box also known as a bastion host or as a control node, and a username to log in with. 

Instead of having to type in the username and password, we are going to set up ssh keys for authentication.
In this lab, ssh keys have been made and put on the end machine.

So first thing we need to do is to check the SSH key from our bastion host to connect to the machines we will be working on.

There are 2 machines we will be connecting to.

* bastion
* node

== 1.2: Create a SSH key pair

From your bastion host, open a terminal

You should see a prompt with your current username and the hostname of the machine you are logged into.

[source,ini,role=execute,subs=attributes+]
----
[lab-user@bastion ~]$
----


We want to find out if the current machine has any ssh keys under the users ‘.ssh’ directory. 

[source,ini,role=execute,subs=attributes+]
----
ls ~/.ssh/
----

‘ls’ is going to list the files under the directory /home/username/.ssh

Next we see there are files in the directrory.

You should now see 2 randomly named files called ‘xxxxxxx.pem’ and ‘xxxxxxx.pub’


[source,textinfo]
----
[lab-user@bastion ~]$ ls ~/.ssh/
authorized_keys  config  xxxxxxx.pem  xxxxxxx.pub 
----


== 1.3 Logging onto node1 

Up to this point we have been using the lab-user account.
On our server we have a different user we need to log in with and then create a dedicated account for our automation services.

First lets go log into the server by opening another terminal and ssh’ing to the server.

 
[source,bash]
----
ssh ec2-user@node1
----

When you log in you should  now see

You should see a prompt with your current username and the hostname of the machine you are logged into.


[source,textinfo]
----
[ec2-user@node1 ~]$
----

You can now exit the node machine by typing,

[source,textinfo]
----
exit
----

Which should take you back to your bastion host.

== 1.4 Install Cockpit Project

We are going to install Cockpit on our bastion machine, which gives us a website to admin our linux system.

Open a terminal on your host machine, and type

[source,ini,role=execute,subs=attributes+]
----
sudo yum install cockpit -y
----

Later in the instructions we will start the service with the command below.
We are leaving it off for now to opimize your machine resources.

[source,ini,role=execute,subs=attributes+]
----
sudo systemctl enable --now cockpit.socket
----

Now we are ready to step into the next section.

