== Common Misconfigurations


=== 5 Threads seen in Red Hat Security Reports

Because we have been writing security reports for so many years, we have been able to note many trends and patterns.


Here are the last few years of Red Hat Product Security Risk Reports

* https://www.redhat.com/en/resources/product-security-risk-report-2022[Red Hat Product Security risk report 2022]
* https://www.redhat.com/en/resources/product-security-risk-report-detail[2021 Red Hat Product Security risk report]
* https://www.redhat.com/en/resources/product-security-risk-report-2020[Red Hat Product Security risk report: 2020]
* https://access.redhat.com/blogs/766093/posts/2695561[Happy 15th Birthday Red Hat Product Security]

The most common issues boiled down are in the following categories:

=== 5.1 Weak Passwords

** Challenge 5.1.1 **

What accounts are on your node1 machine?

** Challenge 5.1.2 **

Of those accounts are they using strong password?

**Resources**

In the past you would check the password with 'pam_cracklib', 
but this should not be used in RHEL 9.

There is a new package you will want to use called 'pam_pwquality'.

* https://access.redhat.com/solutions/6999802[PAM unable to dlopen(/usr/lib64/security/pam_cracklib.so)]
* https://access.redhat.com/solutions/5027331[Set Password Policy & Complexity for RHEL 8 & 9 via pam_pwhistory, pam_pwquality & pam_faillock]
* https://access.redhat.com/solutions/6979714[Set Password Complexity/Policy with pam_pwquality in Red Hat Enterprise Linux 8, 9]


=== 5.2 Permission Issue

** Challenge 5.2.1 **

Of the accounts your found on node1, what permissions do they have?

** Challenge 5.2.2 **

There could be unused accounts with privileges.

**Resources**



=== 5.3 Service Misconfiguration 

** Challenge 5.3.1 **

What are the services is your node1 machine running?

** Challenge 5.3.2 **

What is running on the machine now?


=== 5.4 Neglecting Updates

** Challenge 5.4.1 **

When was your machine last patched and updated?

** Challenge 5.4.2 **

How can you tell?

What can you do if you are in a disconnected network?

You can create your own copy of the repos.
One way to do this is to use our https://access.redhat.com/labs/yumrepoconfighelper/local/[Yum Repository Configuration Helper lab].

==== 5.5 Major CVE's

As part of the ongoing issues that are brought into light from new CVE's,
I'll be writting a blog focusing on a common CVE issue and how it can be handled using Red Hat's built in tools or with ansible.

We will expand this section with those blog posts in the future, so make sure to check back at this lab.

