== Common Misconfigurations

Lab Length
Medium/Average (~10-20 mins)

Goal
Learn about the top Misconfigurations of a machines, how to test for them.

== 5 Threads seen in Red Hat Security Reports

Because we have been writing security reports for so many years, we have been able to note many trends and patterns.


Here are the last few years of Red Hat Product Security Risk Reports

* https://www.redhat.com/en/resources/product-security-risk-report-2022[Red Hat Product Security risk report 2022]
* https://www.redhat.com/en/resources/product-security-risk-report-detail[2021 Red Hat Product Security risk report]
* https://www.redhat.com/en/resources/product-security-risk-report-2020[Red Hat Product Security risk report: 2020]
* https://access.redhat.com/blogs/766093/posts/2695561[Happy 15th Birthday Red Hat Product Security]

We are going to run this playbook on node1, to simulate an inherited machine with misconfiguration.

First we need to make sure curl is installed

[source,ini,role=execute,subs=attributes+]
----
sudo yum install curl -y
----

In our termimal, we are going to our ansible working directory.
[source,ini,role=execute,subs=attributes+]
----
cd ~/ansible
----


Next we are going to pull a playbook that will configure our node1 machine for the upcoming tasks. While you could look at the file and see what ansible is doing, it is better for you to run the playbook, then use your current knowledge to find the issues. After which we will give you ansible playbooks to help you find and fix these common issues.

[source,ini,role=execute,subs=attributes+]
----
curl https://raw.githubusercontent.com/rhpds/summit_2024_RHELevant_Security_Practices_Lab_LB1964/main/content/modules/ROOT/examples/test-lab1.yml -O
----

Next we are going to run this playbook to our node1 machine,

[source,ini,role=execute,subs=attributes+]
----
ansible-playbook -i inventory test-lab1.yml 
----

For the next section We want you to use your access from bastion host to the node1 machine, log into the machine and find out as much of the following as posible. 

The most common issues boiled down are in the following categories:

== 5.1 Weak Passwords

**Challenge 5.1.1**

What accounts are on your node1 machine?

**Challenge 5.1.2**

Of those accounts are they using strong password?

**Resources**

In the past you would check the password with 'pam_cracklib', 
but this should not be used in RHEL 9.

There is a new package you will want to use called 'pam_pwquality'.

* https://access.redhat.com/solutions/6999802[PAM unable to dlopen(/usr/lib64/security/pam_cracklib.so)]
* https://access.redhat.com/solutions/5027331[Set Password Policy & Complexity for RHEL 8 & 9 via pam_pwhistory, pam_pwquality & pam_faillock]
* https://access.redhat.com/solutions/6979714[Set Password Complexity/Policy with pam_pwquality in Red Hat Enterprise Linux 8, 9]


== 5.2 Permission Issue

**Challenge 5.2.1**

Of the accounts your found on node1, what permissions do they have?

**Challenge 5.2.2**

There could be unused accounts with privileges.

**Resources**



== 5.3 Service Misconfiguration 

**Challenge 5.3.1**

What are the services is your node1 machine running?

**Challenge 5.3.2**

What is running on the machine now?


== 5.4 Neglecting Updates

**Challenge 5.4.1**

When was your machine last patched and updated?

**Challenge 5.4.2**

How can you tell?

What can you do if you are in a disconnected network?

You can create your own copy of the repos.
One way to do this is to use our https://access.redhat.com/labs/yumrepoconfighelper/local/[Yum Repository Configuration Helper lab].

== 5.5 Ansible Example

Here is an example on how this could all be done with Ansible

First we should make sure we are on the bastion host, and change the directory to ansible's working.

[source,ini,role=execute,subs=attributes+]
----
cd ~/ansible
----

[source,ini,role=execute,subs=attributes+]
----
vi trust_baseline.yml
----

[source,ini,role=execute,subs=attributes+]
----
---
- name: Check System Configuration and Generate Report
  hosts: localhost
  become: yes
  tasks:
    - name: Check for Users
      command: cat /etc/passwd
      register: users_output

    - name: Check for Groups
      command: cat /etc/group
      register: groups_output

    - name: Check for Shadow File
      command: cat /etc/shadow
      register: shadow_output

    - name: Check for Sudoers File
      command: cat /etc/sudoers
      register: sudoers_output

    - name: Check SELinux Status
      command: getenforce
      register: selinux_status

    - name: Check Enabled Repositories
      command: yum repolist enabled
      register: enabled_repos_output

    - name: Check Patch Level
      command: yum history
      register: yum_history_output

    - name: Generate Report
      template:
        src: system_report.j2
        dest: "{{ ansible_hostname }}_{{ current_date }}_common_misconfigurations_system_report.txt"
----

[source,ini,role=execute,subs=attributes+]
----
vi system_report.j2
----

[source,ini,role=execute,subs=attributes+]
----
System Report:

Users:
{{ users_output.stdout }}

Groups:
{{ groups_output.stdout }}

Shadow File:
{{ shadow_output.stdout }}

Sudoers File:
{{ sudoers_output.stdout }}

SELinux Status:
{{ selinux_status.stdout }}

Enabled Repositories:
{{ enabled_repos_output.stdout }}

Patch Level:
{{ patch_level_output.stdout }}
----

== 5.6 Major CVE's

As part of the ongoing issues that are brought into light from new CVE's,
I'll be writting a blog focusing on a common CVE issue and how it can be handled using Red Hat's built in tools or with ansible.

We will expand this section with those blog posts in the future, so make sure to check back at this lab.

