# Managing Risk & Security Framework


Lab Length
Medium/Average (~10-20 mins)

Goal
Scoping our lab needs for with Risk and Security Frameworks

== Lab 4. Why address risk & security frameworks?

Before we get hand on the box, we need to talk about Risk, Frameworks, and what your are trying to protect yourself from.

First lets go for definitions.

=== 4.1  Governance, Risk, and Compliance (aka GRC)

It's a framework or approach that organizations use to manage and align their business activities with their objectives, manage risk effectively, and comply with regulations and standards.

* **Governance**: Refers to the structure of rules, processes, and decision-making within an organization to ensure that objectives are achieved, risks are managed appropriately, and resources are used responsibly.

* **Risk Management**: Involves identifying, assessing, and mitigating risks that could potentially hinder the achievement of organizational goals. This includes financial risks, operational risks, legal risks, and more.

* **Compliance**: Ensures that organizations adhere to relevant laws, regulations, standards, and internal policies that are applicable to their industry and operations. Compliance efforts aim to prevent legal issues, regulatory fines, and reputational damage.

GRC helps organizations integrate these three elements into their operations to create a structured approach to managing the complexities of running a business while staying in line with legal and ethical standards. That being said, it takes a culture shift to make these changes. Not only the adopotion, but the impelmentation and standardization. 

TL;DR

* Governance - Making and enforcing Business decsions
* Risk - Exposure to danger from loss or harm
* Compliance - Fulfilling requirements from regulation and standards
* Culture - Shared Values, attitudes, goals and practices



== 4.2 Risk management steps

Regardless of the Framework you need to apply, most start with identification.

* **Risk identification**

Identify and describe potential risks. Types of risks could include financial risks, operational risks (such as risks to a supply chain), project risks, business risks, and market risks—among others. Identified risks should be recorded in a risk register or be documented in some way.

* **Risk analysis**

Determine the probability of a new risk happening by analyzing the risk factors and documenting potential consequences.

* **Risk assessment and evaluation**

Using internal audits and risk analysis, determine the magnitude of a risk. You’ll also need to decide what level of risk is acceptable, and what needs to be dealt with immediately.  

* **Risk mitigation**

Once you’ve determined the priority and importance of risks, you can proceed with a risk response strategy to minimize or control the risk. 

* **Risk monitoring**

Risks and metrics need to be continuously monitored to make sure that risk mitigation plans are working, or to keep you aware if a risk becomes a greater threat.


== 4.3 Risk Management Examples


=== 4.3.1 Ransonware

* A hospital can't treat patients because ransomware attacked and their IT infrastructure is not accessable unless they pay.

* An local ice cream parler can't access thier point of sales system due to ransomware.

While both cause business impacts, one is potentally life threating.

=== 4.3.2 Data Loss

* A local dentist office burns down due to an electrical fire along with all their customers medical record.

* A research and development lab developing and supporting equiptment that is used around the world for 20+ years, have an old machine that thier legacy software runs on, and the ancient hard drive dies.

Both are catastrophic issues if there are no backup and tested restores process for the vital business data. 

== 4.4 Compliance Frameworks

There are a lot of different frameworks out there.

* PCI DSS 
* CIS Controls
* ATT&CK 
* NIST Cybersecurity Framework
* Etc.

For more info, check out our page on https://access.redhat.com/articles/compliance_activities_and_gov_standards[Compliance Activities and Government Standards].

== 4.5 How do you pick the right framework?

You have to analyse your risk and pick the one that best fits your org.

That being said, a lot of organisations use and reference the https://www.nist.gov/cyberframework[NIST Cybersecurity Framework (CSF)].

As of Feb 26th 2024 NIST's released CSF version 2.0.

* It's now 32 pages.
* Now have Community Profiles which acts as a 
** baseline of CSF outcomes that is created and published to address shared interests and goals among a number of organizations. 
** typically developed for a particular sector, subsector, technology, threat type, or other use case. 
** An organization can use a Community Profile as the basis for its own Target Profile.
** Examples of https://www.nist.gov/quick-start-guides[Community Profiles can be found on the NIST CSF website].

== 4.6 How is the NIST CSF Connected with RHEL Hardening?

The NIST Cybersecurity Framework (CSF) and the Red Hat Enterprise Linux (RHEL) 9 Security Technical Implementation Guide (STIG) are both important resources in the field of cybersecurity, but they serve slightly different purposes and have different scopes.

=== 4.6.1 NIST Cybersecurity Framework (CSF):

* The NIST CSF is a set of guidelines, standards, and best practices designed to help organizations manage and improve their cybersecurity posture. It provides a framework for organizations to assess and improve their cybersecurity risk management processes.

* The CSF is not specific to any particular technology or platform but offers a flexible structure that can be applied across various industries and organizational contexts.

* It consists of five core functions: Identify, Protect, Detect, Respond, and Recover, which provide a high-level framework for organizing cybersecurity activities.
Red Hat Enterprise Linux 9 Security Technical Implementation Guide (STIG):

=== 4.6.2 Red Hat Enterprise Linux (RHEL) 9 Security Technical Implementation Guide (STIG)

* A STIG is a set of guidelines and configuration standards developed by the Defense Information Systems Agency (DISA) for securing computer systems and software.

* The RHEL 9 STIG specifically provides detailed security configuration requirements and recommendations for securing Red Hat Enterprise Linux 9 systems.

* It covers a wide range of security controls and settings, including network configuration, user authentication, file permissions, logging, and many others.

* The STIG is typically used by government agencies and organizations that need to comply with stringent security requirements, especially those related to the U.S. Department of Defense (DoD).

=== 4.6.3 Wrap up definition 

While the NIST CSF provides a high-level framework for cybersecurity risk management, the RHEL 9 STIG offers detailed guidance on implementing security controls specific to Red Hat Enterprise Linux 9 systems. 

Organizations can use the CSF to establish their cybersecurity policies and objectives and then use resources like the RHEL 9 STIG to implement specific security measures aligned with those objectives on their RHEL 9 systems. 

In this way, the NIST CSF and the RHEL 9 STIG can complement each other in helping organizations improve their overall cybersecurity posture.

Now that we have theory and definition out of the way.

Just because have have picked a framework, this does not mean that we are 100% safe or protected.

We will see a few example of how the Framework does not secure the machine, more on that later in the lab workshops.

We will be using the RHEL 9 STIG with ansible to harden on our systems, with the understanding that we will have to make some changes for our test lab environment. 

=== 4.7 Configuration compliance in RHEL 

You can use configuration compliance scanning to conform to a baseline defined by a specific
organization. For example, if you work with the US government, you might have to align your systems
with the Operating System Protection Profile (OSPP), and if you are a payment processor, you might
have to align your systems with the Payment Card Industry Data Security Standard (PCI-DSS). You can
also perform configuration compliance scanning to harden your system security.

Red Hat recommends you follow the Security Content Automation Protocol (SCAP) content provided
in the SCAP Security Guide package because it is in line with Red Hat best practices for affected
components.

You can modify (tailor) a profile to customize certain rules, for example, password length. For more
information about profile tailoring, see Customizing a security profile with SCAP Workbench .

=== 4.7.1 Install OpenSCAP on RHEL 9

In this step we will install OpenSCAP on your bastion host.

[source,ini,role=execute,subs=attributes+]
----
sudo yum install openscap-scanner -y
----

Then we are going to install the content and profiles onto your bastion host

[source,ini,role=execute,subs=attributes+]
----
sudo yum install scap-security-guide -y
----

If you want to see what profiles are avaible to you

[source,ini,role=execute,subs=attributes+]
----
sudo oscap info /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml 
----

This should put out a large list of options like below:

[source,textinfo]
----
<---------Output_Abbreviated------------------->
Document type: Source Data Stream
Imported: 2024-02-14T11:42:50

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-rhel9-xccdf.xml
Generated: (null)
Version: 1.3
Checklists:
        Ref-Id: scap_org.open-scap_cref_ssg-rhel9-xccdf.xml
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-v2-RHEL9-rhel-9.oval.xml.bz2' points out to the remote 'https://access.redhat.com/security/data/oval/v2/RHEL9/rhel-9.oval.xml.bz2'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://access.redhat.com/security/data/oval/v2/RHEL9/rhel-9.oval.xml.bz2' file which is referenced from datastream
                Status: draft
                Generated: 2024-02-14
                Resolved: true
                Profiles:
                        Title: ANSSI-BP-028 (enhanced)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_enhanced
                        Title: ANSSI-BP-028 (high)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_high
                        Title: ANSSI-BP-028 (intermediary)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_intermediary
                        Title: ANSSI-BP-028 (minimal)
                                Id: xccdf_org.ssgproject.content_profile_anssi_bp28_minimal
                        Title: CCN Red Hat Enterprise Linux 9 - Advanced
                                Id: xccdf_org.ssgproject.content_profile_ccn_advanced
                        Title: CCN Red Hat Enterprise Linux 9 - Basic
                                Id: xccdf_org.ssgproject.content_profile_ccn_basic
                        Title: CCN Red Hat Enterprise Linux 9 - Intermediate
                                Id: xccdf_org.ssgproject.content_profile_ccn_intermediate
                        Title: CIS Red Hat Enterprise Linux 9 Benchmark for Level 2 - Server
                                Id: xccdf_org.ssgproject.content_profile_cis
                        Title: CIS Red Hat Enterprise Linux 9 Benchmark for Level 1 - Server
                                Id: xccdf_org.ssgproject.content_profile_cis_server_l1
                        Title: CIS Red Hat Enterprise Linux 9 Benchmark for Level 1 - Workstation
                                Id: xccdf_org.ssgproject.content_profile_cis_workstation_l1
                        Title: CIS Red Hat Enterprise Linux 9 Benchmark for Level 2 - Workstation
                                Id: xccdf_org.ssgproject.content_profile_cis_workstation_l2
                        Title: DRAFT - Unclassified Information in Non-federal Information Systems and Organizations (NIST 800-171)
                                Id: xccdf_org.ssgproject.content_profile_cui
                        Title: Australian Cyber Security Centre (ACSC) Essential Eight
                                Id: xccdf_org.ssgproject.content_profile_e8
                        Title: Health Insurance Portability and Accountability Act (HIPAA)
                                Id: xccdf_org.ssgproject.content_profile_hipaa
                        Title: Australian Cyber Security Centre (ACSC) ISM Official
                                Id: xccdf_org.ssgproject.content_profile_ism_o
                        Title: Protection Profile for General Purpose Operating Systems
                                Id: xccdf_org.ssgproject.content_profile_ospp
                        Title: PCI-DSS v4.0 Control Baseline for Red Hat Enterprise Linux 9
                                Id: xccdf_org.ssgproject.content_profile_pci-dss
                        Title: DISA STIG for Red Hat Enterprise Linux 9
                                Id: xccdf_org.ssgproject.content_profile_stig
                        Title: DISA STIG with GUI for Red Hat Enterprise Linux 9
                                Id: xccdf_org.ssgproject.content_profile_stig_gui
                Referenced check files:
                        ssg-rhel9-oval.xml
                                system: http://oval.mitre.org/XMLSchema/oval-definitions-5
                        ssg-rhel9-ocil.xml
                                system: http://scap.nist.gov/schema/ocil/2
                        security-data-oval-v2-RHEL9-rhel-9.oval.xml.bz2
                                system: http://oval.mitre.org/XMLSchema/oval-definitions-5
Checks:
        Ref-Id: scap_org.open-scap_cref_ssg-rhel9-oval.xml
        Ref-Id: scap_org.open-scap_cref_ssg-rhel9-ocil.xml
        Ref-Id: scap_org.open-scap_cref_ssg-rhel9-cpe-oval.xml
        Ref-Id: scap_org.open-scap_cref_security-data-oval-v2-RHEL9-rhel-9.oval.xml.bz2
Dictionaries:
        Ref-Id: scap_org.open-scap_cref_ssg-rhel9-cpe-dictionary.xml

<---------Output_Abbreviated------------------->
----

[source,ini,role=execute,subs=attributes+]
----
sudo oscap xccdf eval  --profile <profile_name> --results <results_file.xml> /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
----

