== Ansible 101

=== Introduction to Ansible

Ansible provides open-source automation that reduces complexity and runs everywhere. 

Using Ansible lets you automate virtually any task. 

Here are some common use cases for Ansible:

* Eliminate repetition and simplify workflows
* Manage and maintain system configuration
* Continuously deploy complex software
* Perform zero-downtime rolling updates

Ansible uses simple, human-readable scripts called playbooks to automate your tasks. 

You declare the desired state of a local or remote system in your playbook. 

Ansible ensures that the system remains in that state.

As automation technology, Ansible is designed around the following principles:

* **Agent-less architecture** 
** Low maintenance overhead by avoiding the installation of additional software across IT infrastructure.

* **Simplicity**
** Automation playbooks use straightforward YAML syntax for code that reads like documentation. Ansible is also decentralized, using SSH existing OS credentials to access to remote machines

* **Scalability and flexibility**
** Easily and quickly scale the systems you automate through a modular design that supports a large range of operating systems, cloud platforms, and network devices.

* **Idempotence and predictability**
** When the system is in the state your playbook describes Ansible does not change anything, even if the playbook runs multiple times.

To learn more about ansible check out the Official https://docs.ansible.com/ansible/latest/getting_started/basic_concepts.html[Ansible Commnity Documentation]

We are going to make sure you can get Ansible Installed on RHEL 9.


=== Install Ansible for Red Hat Enterprise Linux 9

If you use Ansible content within Red Hat Enterprise Linux (RHEL), 
you should know that important changes where made with RHEL 8.6 and 9.0.

RHEL 7 and RHEL 8.0-8.5 customers have access to a separate Ansible Engine repository. 

In RHEL 8.6 and 9.0, customers will have access to Ansible Core, which will be included in the corresponding AppStream repository. 

The move to Ansible Core in RHEL is being made to adapt to changes in the Ansible project.

** What is the difference between Ansible core and engine? **
Long story short,

You'll be using Ansible core with RHEL 9, so lets get it installed.

[source,ini,role=execute,subs=attributes+]
----
sudo dnf install ansible-core -y
----


=== Basic Ansible setup for Red Hat Enterprise Linux 9

I like to create a working directory to work on my ansible projects in my home folder

[source,ini,role=execute,subs=attributes+]
----
mkdir ~/ansible
----

I also then like bring in a deafult ansible config file for later use.

[source,ini,role=execute,subs=attributes+]
----
ansible-config init --disabled > ansible.cfg
----

We also need to create an inventory file to refference.

The inventory file is where we list our machines we will connect to.

In this lab we will connect to 

* bastion
* node1

To Create the most simple inventory file use your favorite editer,

[source,ini,role=execute,subs=attributes+]
----
vi ~/ansible/inventory
----

Once you have the file opened past the following

[source,ini,role=execute,subs=attributes+]
----
[bastion]
localhost


[nodes]
YourNode1IPaddress

----
Save and close the file



== Reference Documentation

https://www.redhat.com/en/blog/updates-using-ansible-rhel-86-and-90[Updates to using Ansible in RHEL 8.6 and 9.0]

https://www.redhat.com/en/blog/updates-using-ansible-core-in-rhel[Updates to using Ansible Core in Red Hat Enterprise Linux]

https://access.redhat.com/articles/6393321[Using Ansible in RHEL 9]

https://access.redhat.com/articles/3050101[Red Hat Enterprise Linux (RHEL) System Roles]



